language: c
notifications:
   slack: skydreams:1FLUnEeqaNLinKq1p0lJf9F5
services:
 - docker
env:
 - USEDOCKER="yes" PROFILE="default" DOCKER_IMAGE="dellelce/mkit" PREFIX="/app/httpd"
 - USEDOCKER="yes" PROFILE="postgres" DOCKER_IMAGE="dellelce/pgbase" PREFIX="/app/pg"
 - USEDOCKER="yes" PROFILE="uwsgi" DOCKER_IMAGE="dellelce/uwsgi" PREFIX="/app/uwsgi"
 - USEDOCKER="yes" PROFILE="openvpn" DOCKER_IMAGE="dellelce/openvpnbase" PREFIX="/app/openvpn"
 - USEDOCKER="no" PREFIX="/tmp/build"
script: ./travis-plex.sh "$USEDOCKER"
