language: c
notifications:
   slack: skydreams:1FLUnEeqaNLinKq1p0lJf9F5
branches:
 only:
  - master
services:
 - docker
env:
 - USEDOCKER="yes" PROFILE="haproxy" DOCKER_IMAGE="dellelce/haproxy-base" PREFIX="/app/haproxy"
 - USEDOCKER="yes" PROFILE="default" DOCKER_IMAGE="dellelce/mkit" PREFIX="/app/httpd"
 - USEDOCKER="yes" PROFILE="python" DOCKER_IMAGE="dellelce/py-base" PREFIX="/app/python"
 - USEDOCKER="yes" PROFILE="timescaledb" DOCKER_IMAGE="dellelce/timescaledb-base" PREFIX="/app/pg"
 - USEDOCKER="yes" PROFILE="uwsgi" DOCKER_IMAGE="dellelce/uwsgi" PREFIX="/app/uwsgi"
 - USEDOCKER="yes" PROFILE="openvpn" DOCKER_IMAGE="dellelce/openvpnbase" PREFIX="/app/openvpn"
# - USEDOCKER="yes" PROFILE="bind" DOCKER_IMAGE="dellelce/bindbase" PREFIX="/app/bind"
 - USEDOCKER="yes" PROFILE="cairo" DOCKER_IMAGE="dellelce/cairobase" PREFIX="/app/cairo"
# - USEDOCKER="yes" PROFILE="opengl" DOCKER_IMAGE="dellelce/opengl-base" PREFIX="/app/opengl"
 - USEDOCKER="yes" PROFILE="libgit2" DOCKER_IMAGE="dellelce/libgit2-base" PREFIX="/app/libgit2"
 - USEDOCKER="yes" PROFILE="mosquitto" DOCKER_IMAGE="dellelce/mosquitto-base" PREFIX="/app/mosquitto"
 - USEDOCKER="no" PREFIX="/tmp/build"
before_script:
 - mkdir /tmp/build && sudo mount -t tmpfs tmpfs /tmp/build
 - sudo ./travis-tmpfs.sh
 - ( ( while true; do echo -e  "\e[31mtravis ping $(date +%H%M%S)\e[0m"; ps -eo args | awk '/wget/&&!/awk/'; sleep 30; [ -f end ] && break; done; ) & )
script: ./mkit-wrapper.sh "$USEDOCKER"
