language: c
notifications:
   slack: skydreams:1FLUnEeqaNLinKq1p0lJf9F5
services:
 - docker
env:
 - USEDOCKER="yes" PROFILE="haproxy" DOCKER_IMAGE="dellelce/haproxy-base" PREFIX="/app/haproxy"
 - USEDOCKER="yes" PROFILE="default" DOCKER_IMAGE="dellelce/mkit" PREFIX="/app/httpd"
 - USEDOCKER="yes" PROFILE="python" DOCKER_IMAGE="dellelce/py-base" PREFIX="/app/python"
 - USEDOCKER="yes" PROFILE="postgres" DOCKER_IMAGE="dellelce/pgbase" PREFIX="/app/pg"
 - USEDOCKER="yes" PROFILE="uwsgi" DOCKER_IMAGE="dellelce/uwsgi" PREFIX="/app/uwsgi"
 - USEDOCKER="yes" PROFILE="openvpn" DOCKER_IMAGE="dellelce/openvpnbase" PREFIX="/app/openvpn"
 - USEDOCKER="yes" PROFILE="bind" DOCKER_IMAGE="dellelce/bindbase" PREFIX="/app/bind"
 - USEDOCKER="no" PREFIX="/tmp/build"
script: ./mkit-wrapper.sh "$USEDOCKER"
